#apache/php
sf_web:
    build: apache-php
    container_name: "sf_web"
    hostname: "sf3"
    ports:
        - 8080:80   #apache
        - 9001:9000 #xdebug
    volumes:
        - "../www:/var/www/html/www"
        - "~/.composer:/var/www/.composer"
        - "./data/.cache:/var/www/.cache"
        - "./data/.config:/var/www/.config"
        - "./data/.local:/var/www/.local"
        - "./data/.npm:/var/www/.npm"
#    links:
#        - db
#        - mailcatcher
    env_file:
        - docker-env

##mysql
#db:
#    image: mariadb:latest
#    container_name: "sf_db"
#    ports:
#    - 3306
#    environment:
#        MYSQL_DATABASE: sf3
#        MYSQL_USER: sf3
#        MYSQL_PASSWORD: sf3
#        MYSQL_ROOT_PASSWORD: root
#    volumes:
#    - ./data/sql:/var/lib/mysql
#    - ./mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf
#
##mailcatcher
#mailcatcher:
#    image: yappabe/mailcatcher
#    container_name: "sf_mailcatcher"
#    ports:
#        - 1025:1025
#        - 1080:1080

